export const LABELS_PLAYER = {
    en: {
		remember: "Remember Me",
		forgotPass: "Forgot Password?",
		dontHavAcc: "Do not have an account?",
		signupNow: "Sign Up Now!",
		signupTitle: "Sign Up",
		loginTitle: "Login",
		loginOtpScreenTitle: "Verify OTP to Sign In",
		forgetPassTitl: "Reset Password",
		placeholderEmail: "Email ID",
		placeholderPassword: "Password",
		placeholderNewPassword: "New Password",
		placeholderCurrentPassword: "Current Password",
		placeholderFirstname: "First name",
		placeholderLastname: "Last name",
		placeholderPasswordC: "Confirm Password",
		btnCancel: "Cancel",
		btnPayment: "Upgrade plan",
		btnSubmit: "Submit",
		btnSignup: "Sign Up",
		btnLogin: "Login",
		loginWithGuideMe: "Login with ",
		signupTerms: "I agree to the EdCast",
		termsOfUse: "Terms of Use",
		andLabel: "and",
		policyPrivacy: "Privacy Policy",
		passwordError: "Password must be 8 digit long",
		confirmPasswordError: "Password and confirm password must be same",
		signupTermError: "Please check Terms and Condition",
		firstnameError: "Please enter a valid first name",
		lastnameError: "Please enter a valid last name",
		emailError: "Please enter a valid Email ID",
		orgError: "Please enter a valid Organization URL",
		otpError: "Please enter valid OTP",
		placeholderOtp: "Enter your OTP here",
		otpSentDesc: "If a valid email address has been provided, a reset link will be sent to you.<br>If you do not see the email in a few minutes, please check your spam folder for an email from admin@edcast.com",
		btnOtpVerify: "Verify OTP",
		alreadyHavAcc: "Already have an account?",
		smartbiteMessageError: "Please enter message",
		smartbiteLinkError: "Please enter valid link",
		noGuidesOnThisPage: "No Guides Available on this page!",
		noGuidesOnThisPageHPE: "For help please contact your administrator",
		clickOn: "Click on ",
		setUpTeam: "To set up your Team/Org on EdCast:",
		contactUs: "Contact Us",
		search: "Search",
		createSmartBite: "Create",
		createArticleInsight: "Create an article insight",
		articleLink: "Article Link",
		create: "Create",
		noRecordFound: "No records found",
		guide: "Guide",
		category: "Folder",
		subCategory: "Sub Folder",
		confirmPasswordRequired: "Confirm Password Required",
		logInUsingEdCast: "Login with EdCast",
		logInUsingSpark: "Login with Spark",
		logInWithSSO: "Login with SSO",
		edcastSsoNotEnable: "EdCast SSO is not enabled for this organization",
		invalidEdOrg: "Invalid URL",
		testMe: "TestMe",
		showMe: "ShowMe",
		guideMe: "GuideMe",
		vLab: "TeachMe",
		doItForMe: "DoItForMe",
		inputPlaceHolderSearch: "Search",
		noGuideAvailableFor: "No guides were found to match your search",
		tryModifyingYourSearch: "Try modifying your search criteria",
		currentPage: "Current Page",
		signInVerifyYourEmail: "This Email ID has not been verified. Please check your email for details",
		signUpVerifyYourEmail: "We have sent you an email with a confirmation link. Please verify your email to complete the Sign Up process",
		signInVerifyYourAccount: "We have sent you an email with an OTP. Please verify your account to complete the Sign In process",
		disableLoginThirtyMessage: "This account has been temporarily deactivated due to too many invalid login attempts. Please try again in 30 minutes",
		maintenanceMessage: "Maintenance in progress. Please contact us via support@edcast.com",
		back: "Back",
		changePassword: "Change password",
		startTestAuto: "Start Automation Testing",
		testAuto: "Test Automation",
		testAutoConfig: "Configure",
		enableAutoSteps: "Enable automation steps",
		automationSection: "Automation",
		msgPasswordChangedSuccess: "Your password has been changed successfully",
		msgConfirmNewPasswordError: "Confirm Password must be the same as New Password",
		enterUrl: 'Enter team URL',
		dragPlaceholderDropThis: "Drop this ",
		dragPlaceholderHere: " here",
		guideMeByEdCast: 'GmXt.conf.brandName',
		separator: " | ",
		privacyPolicy: "Privacy",
		termsOfService: "Terms",
		aboutMyguide: "About " + 'GmXt.conf.dap',
		versionText: "Version",
		videoStepSuccessMessage: "Your step created successfully",
		importSuccessMessage: "Guide uploaded successfully. Go to Task Status to check import status",
		import: "Import",
		export: "Export",
		worldBankTitle: "Welcome to the iGuide Content Panel",
		worldBankDescription: "This panel provides users with an alternate way to view applicable iGuide learning tools such as step-by-step walk-through, slide demos, videos, etc",
		iGuidesHowToVideo: "iGuides How to video",
		iGuidesFAQs: "iGuides FAQs",
		worldBankHelpSupport: "Some tools, such as tooltips, can only be viewed in the interface",
		helpSupport: "Help & Support",
		page: "page",
		selectAnApplication: "Select an Application",
		refresh: "Refresh",
		loginBtn: "Login",
		headerLangEnglish: "English",
		headerLangRussian: "Russian",
		account: "Account",
		manageAccount: "Admin portal",
		taskStatus: "Task status ",
		logoutBtn: "Logout",
		app: "App:",
		firstStep: "First Step",
		lastStep: "Last Step",
		startTest: "Start Test",
		noInappStepInGuide: "TestMe cannot proceed, since there is no inline steps in this guide",
		settingBtn: "Settings",
		orgSetting: "Organization settings",
		close: "Close",
		downloadVideo: "Video",
		downloadPdf: "PDF",
		downloadPptx: "PPT",
		downloadGif: "GIF",
		downloadWord: "Document",
		downloadBlog: "Blog",
		downloadTxt: "Plain text",
		serviceErrorMessage: "Oops! An error occurred. Please try again after some time. You can also email us at support@edcast.com for any assistance",
		AllGuidesTab: "Guides",
		noGuideCreatedYet: "No Guide created yet!",
		noCategoryCreatedYet: "No Folder created yet!",
		knowledgeCloud: "LXP",
		chatbot: "MyChat",
		notAutorised: "You do not have the required access, please contact the administrator",
		btnOk: "OK",
		logoutPopContent: "Do you really want to logout?",
		emailPostfix: "@dotfoods.com",
		apiError: "Configuration error. Please contact the administrator",
		select: "Select",
		mute_unmute: "Mute/Un-Mute",
		cookie: "Cookies",
		privacyPolicyText: 'GmXt.conf.dap' + " uses cookies. If you continue, you are agreeing to our",
		terms: "Terms",
		consentToUseCookies: "and giving us consent to use cookies",
		westPecErrorMessage: "You are not authorised to access this application. Please sign into Westpac's network",
		hpeLogoTitle: "Guide & Go",
		hpeTitle: "Welcome to Guide & Go!",
		hpeDescription: "Guide & Go is a just-in-time learning resource available across multiple applications. It provides guidance as you navigate the application.<div class='gss-banner-description gss-description-margin'>Use <div class='gss-text-highlight gss-inline-block-vt'>Guide Me</div> to receive step-by-step instructions while you complete the task. Use <div class='gss-text-highlight gss-inline-block-vt'>Show Me</div> to preview the process steps (slideshow or video).</div><div class='gss-banner-description gss-description-margin'>The list shows the guide(s) available for the page you are currently on.</div>",
		applicationMyGuide: 'GmXt.conf.dap',
		noApp: "No Applications found",
		role: "Role:",
		all: "All",
		video: "Video",
		course: "Course",
		article: "Article",
		image: "Image",
		pathways: "Pathways",
		chooseChannel: "Choose a Channel",
		preview: "Preview",
		more: "More",
		history: "History",
		publish: "Publish",
		selectGuideLink: "Please select guide to link",
		selectGuideBeforeSubmit: "Please select a guide before submit",
		change: "Change",
		checkNow: "Check Now",
		accountDisabled: "This account has been temporarily deactivated due to too many invalid login attempts. Please try again in",
		minutes: "minutes",
		clickHere: "click here",
		supportEdcast: "support@edcast.com",
		youAlmostDone: "You're almost done!",
		setOrg: "to set up your Organization",
		apps: "Apps",
		me: "Me",
		embededForceTooltip: 'DoItForMe is not available when Force slideshow mode is enabled.',
		playStep: "Play Step",
		paymentPopTitle: "Upgrade to Premium",
		guideLimitReach: "Guides publishing limit is Exceeded",
		paymentPopDesc: "Subscribe to our premium plan to publish unlimited Guides and access all the advanced features of" + 'GmXt.conf.dap',
		miniPlayerHelp: "Help",
		defaultMiniPlayerHelp: "Help",
		defaultConfirmIfSlideshowOrRedirect: "Step not available on current URL.<br>Do you want to go to the Step URL or play slideshow?",
		defaultServiceErrorMessage: "Oops! An error occurred. Please try again after some time. You can also email us at support@edcast.com for any assistance",
		defaultMaintenanceMessage: "Maintenance in progress. Please contact us via support@edcast.com",
		defaultUserNotFollowingGuideMessage: "It looks like you're performing steps that are not part of this guide. If you no longer wish to follow the guide, click on Exit Guide",
		defaultTestMe: "TestMe",
		defaultShowMe: "ShowMe",
		defaultGuideMe: "GuideMe",
		defaultVLab: "TeachMe",
		defaultDoItForMe: "DoItForMe",
		defaultKnowledgeCloud: "LXP",
		resumeGuideMessage: "Resume Guide",
		defaultResumeGuideMessage: "Resume Guide",
		exportNoStepsMessage: 'GmXt.conf.dap' + " cannot export an empty guide",
		backToLogin: "Back to Login",
		filters: "Filters",
		thisApp: "This App",
		thisWebsite: "This Website",
		maxFreeTourLimit: "Max limit of tours reached",
		passwordRegexCheck: "The password must contain a minimum of 8 characters, including at least one uppercase, one lowercase and one numeric value",
		countLimit: "99+",
		microsoftServiceKey: "Please enter your Microsoft Cognitive Services Speech subscription key",
		numberOfImgFile: "Number of image files and text files should be same",
		availableOn: "Available on",
		tooltipUnpubWorkflowTitle: "Unpublished Workflow",
		tooltipUnpubWorkflowDesc: "Use a Workflow Guide to perform a step-by-step workflow",
		tooltipUnpubParentWorkflowTitle: "Published Workflow, Unpublished Parent Folder(s)",
		tooltipUnpubParentWorkflowDesc: "Performs a step-by-step Workflow",
		tooltipPubParentWorkflowTitle: "Published Workflow, Published Folder",
		tooltipPubParentWorkflowDesc: "Performs a step-by-step workflow",
		tooltipUnpubTooltipTitle: "Unpublished Tooltip",
		tooltipUnpubTooltipDesc: "Use a Tooltip Guide to place a static callout box on the application window",
		tooltipUnpubParentTooltipTitle: "Published Tooltip, Unpublished Parent Folder(s)",
		tooltipUnpubParentTooltipDesc: " Places a static callout box on the application window",
		tooltipPubParentTooltipTitle: "Published Tooltip, Published Folder",
		tooltipPubParentTooltipDesc: "Places a static callout box on the application window",
		tooltipUnpubTutorialTitle: "Unpublished Tutorial",
		tooltipUnpubTutorialDesc: "Use a Tutorial Guide to auto-play a fullscreen pop-up slideshow with a “Next” Tutorial option",
		tooltipUnpubParentTutorialTitle: "Published Tutorial, Unpublished Parent Folder(s)",
		tooltipUnpubParentTutorialDesc: "Auto-plays a fullscreen pop-up slideshow with “Next” Tutorial option",
		tooltipPubParentTutorialTitle: "Published Tutorial, Published Folder",
		tooltipPubParentTutorialDesc: "Auto-plays a full-screen pop-up slideshow with “Next” Tutorial option",
		tooltipUnpubSubFolderTitle: "Unpublished Sub-folder",
		tooltipUnpubSubFolderDesc: "Use sub-folders to organize Guides",
		tooltipUnpubParentSubFolderTitle: "Published Sub-folder, Unpublished Parent Folder(s)",
		tooltipUnpubParentSubFolderDesc: "Organizes Guides",
		tooltipPubParentSubFolderTitle: "Published Sub-folder, Published Folder",
		tooltipPubParentSubFolderDesc: "Organizes Guides",
		exitSurvey: 'Exit Survey',
		disable: "Disable",
		instructionExitSurvey: "Exit Survey is is shown when a user exit's a guide before completion",
		msgVideoNotFound: "Uploading your video, please try after some time",
		msgGiphyNotFound: "Uploading your giphy, please try after some time",
		edcastApiError: "Authentication error. Please try to login again",
		youtubePublishMessage: "Your video will be published on YouTube",
		videoNotAvail: "Video is not available for publishing on YouTube",
		wbViewiGuideInfo: "View iGuide info",
		wbiGuideTools: "iGuide Tools",
		wbWalkThrus: "Walk-thrus & demos",
		wbTooltips: "Tooltips",
		wbVideos: "Videos",
		wbPopupNotification: "Pop-up notifications &",
		wbMessages: "messages",
		saveConf: "Save",
		userPref: "My Preferences",
		cdnUrl: "Cdn Url",
		appKey: "App Key",
		apiUrl: "API Url",
		analyticsUrl: "Insights Url",
		webPortal: "Admin portal",
		analyticsPortal: "Insights portal",
		errorInvalidUrl: "Not a valid URL",
		wbFooterText: "ITS Technical Learning",
		navigationMenu: "Navigation menu",
		enableSearchResult: "LXP Search Results",
		clearHistory: "Clear History",
		userDeniedMessage: "User denied Camera and Microphone access permissions",
		pushNotification: "Push Notification",
		viewDetail: "View Detail",
		contactAdmin: "Please contact <a class='gss-contact-info gss-font-size-16 gss-theme-color' target='_top' href='mailto:support@edcast.com'>support@edcast.com</a> or your admin for further assistance",
		noAppOnDomain: "Application is not assigned for current domain ",
		noGuidesOnDomain: "No Guides found",
		apply: "Apply",
		teamUrlError: "Please enter a valid organization URL",
		invalidLoginCred: "Invalid login credentials. Please try again",
		resendOTP: "Resend OTP",
		goToLib: "All Guides",
		goToThisPage: "Current Page",
		sendFeedback: 'Send Feedback',
		guideNotExist: "This guide is not available on this page (Error: Domain mismatch) ",
		cdnAccess: "<b>We're sorry</b> <br><br>It seems there is problem with our servers.<br> We've been notified of the error and will correct it as soon as possible",
		tourPlayError: "Guide can not be played. Error while retrieving guide details",
		playerMode: "Player mode",
		closePanel: "Close panel",
		switchCreatorMode: "Switch to Creator Mode",
		extensionContextError: "Extension context is invalidated. Please reload the page to continue",
		otpSent: "OTP has been re-sent to your email, please check your inbox",
		startOver: "Start Again",
		yesResume: "Resume",
		resumeGuide: "You have played this guide before, resuming it will continue the guide from the last played step.",
		dontShowAgain: "Don't show again",
		notificationHeader: "You've got a notification!",
		watchLater: "Watch later",
		pushSnoozeMsg: "This notification will be snoozed for",
		showAgain: "Show again",
		noGuidesOnThisTab: "There are no notifications on this page",
		iAgree: "I Agree",
		viewMore: "View More",
		lostInternetConnection: "Lost connection to the server. Please reconnect and try again",
		next: "Next",
		recent: "Recent",
		older: "Older",
		atoz: "A - Z",
		ztoa: "Z - A",
		clear: "Clear",
		tooltipDontShowAgain: "Notifications won't appear anymore. To enable a notification now, hover over it and click on 'Show Again'",
		tooltipWatchLater1: "Notifications are snoozed for",
		tooltipWatchLater2: "and will appear after that. To enable a notification now, hover over it and click on 'Show Again'",
		hour: "hour",
		hours: "hours",
		insightsTracker: "Insights Tracker",
		giphy: "GIF",
		slideshow: "SlideShow",
		autoplay: "AUTOPLAY",
		powerFormOldData: "Existing data",
		powerFormNewData: "Use this form to enter new data",
		powerFormNewDataMore: "If your existing data is not visible, please click on the arrow in the top left to view your data. The data then needs to be copied across into the permitted bulleted format.",
		powerFormTitle: "Data Entry Assistant",
		powerFormMandatory: "This is a mandatory field, max character limit ",
		automationGuideAndStepEnabled: "Enable automation guide and step",
		belongToOtherApp: "This guide is created on <strong>{TOURURL}</strong>, which belongs to the <strong>{APPNAME}</strong> app. Please copy this guide in that app and try again",
		setDomain: "If you are sure that the <strong>{TOURURL}</strong> should be added in the current application domain settings, please add and try again",
		on: "ON",
		off: "OFF",
		btnPrev: "Prev",
		btnNext: "Next",
		btnDone: "Close",
		btnPrevious: "Previous",
		taskList: "Task List",
		unprocessedVideo: "Please wait while your video is being processed.",
		orgUrlIsEmpty: "Organization URL is empty",
		searchResult: "Search Result"
	}
};

export const LABELS_PLAYER_AUTO = {
    en: {
		importSuccessMessage: "Task uploaded successfully. Go to Task Status to check import status"
	}
};

export const LABELS_PLAYER_IN = {
	en: {
		AllGuidesTab: "Workflow",
		noGuideCreatedYet: "No Workflow created yet!",
		noGuidesOnThisPage: "No workflow on this page!",
		guide: "Workflow",
		inputPlaceHolderSearch: "Search Workflow",
		noGuideAvailableFor: "No workflow were found to match your search"
	}
};

export const LABELS_ERROR_REPORT = {
	en: {
		403: "We ran into a problem with this request. Please try this again. If the problem persists report to us at support@edcast.com",
		405: "We ran into a problem while processing this request. Please try this again. If the problem persists report to us at support@edcast.com",
		1003: "We ran into a problem during authentication. Please re-login and try again. If the problem persists refresh the page and try again",
		1007: "We ran into a problem during authentication. Please try again. If the problem persists report to us at support@edcast.com",
		1005: "<b>We're sorry</b> <br><br>It seems there is problem with the request or with our servers.<br> We've been notified of the error and will correct it as soon as possible",
		1009: "User email is not verified",
		1014: "Maintenance in progress. Please contact us via support@edcast.com",
		1017: "We ran into a problem during authentication. Please re-login and try again. If the problem persists report to us at support@edcast.com",
		1018: "You have reached the maximum limit to create steps",
		2000: "We ran into a problem with this request. We have been notified. Please try this again. If the problem persists report to us at support@edcast.com",
		2001: "Invalid login credentials. Please try again",
		2002: "Invalid or expired OTP",
		2003: "Uploaded file is not a valid image (JPG and PNG files are supported)",
		2004: "Session expired",
		2005: "We could not track this user. Please refresh and try again. If the problem persists report to us at support@edcast.com",
		2006: "Email Address incorrect. Please try again",
		2007: "User Role invalid. Please try again",
		2008: "You must specify a correct Task type",
		2009: "The given Application is invalid, it could have been deleted or never existed",
		2010: "Invalid input parameters. Please refresh and try again. If the problem persists report to us at support@edcast.com",
		2011: "The given Organization is invalid: it could have been deleted or never existed",
		2012: "There was a missing or invalid parameter in the request. Please re-check and try again. If the problem persists report to us at support@edcast.com",
		2013: "There was a missing or invalid parameter in the request. Please re-check and try again. If the problem persists report to us at support@edcast.com",
		2014: "Parameter required for Super Admin[organization_id]",
		2015: "Image Data content provided is invalid. Please re-check and try again. If the problem persists report to us at support@edcast.com",
		2016: "Invalid Domain",
		2017: "There was a missing or invalid parameter in the request",
		2018: "There was a missing or invalid parameter in the request",
		2019: "What you are looking for does not exist or might have been deleted",
		2020: "There was a missing or invalid parameter in the request",
		2021: "The Authentication server encountered an unexpected error while trying to process this request. Please report the problem to support@edcast.com",
		2022: "There was a missing or invalid parameter in the request. Please enter a valid Team URL",
		2023: "The Authentication server encountered an unexpected error while trying to process this request. Please report the problem to support@edcast.com",
		2024: "File size should be less than 5 MB",
		2025: "There was a missing or invalid parameter in the request. Please enter a valid URL",
		2026: "The password must contain a minimum of 8 characters, including at least one uppercase, one lowercase and one numeric value",
		2027: "Invalid Password",
		2028: "There was a missing or invalid parameter in the request",
		2029: "The City you have provided is not supported",
		2030: "There was a missing or invalid parameter in the request",
		2031: "The Authentication server encountered an unexpected error while trying to process this parameter. Please report the problem to support@edcast.com",
		2032: "Invalid parameter[file_id]",
		2033: "Invalid URL. Please re-check and try again",
		2034: "The Authentication server encountered an unexpected error, while trying to process these parameters. Please report the problem to support@edcast.com",
		2035: "The Authentication server encountered an unexpected error, while trying to process this AppKey. Please report the problem to support@edcast.com",
		2036: "The Authentication server encountered an unexpected error. Please refresh this page. If the problem persists report the problem to support@edcast.com",
		2044: "We seem to have misplaced the translation for this step. Please switch to Default Language and re-translate the step or contact our customer support for futher details.",
		2200: "We ran into a problem while accessing audio/video controls. Please check your browser settings and try this again. If the problem persists report to us at support@edcast.com",
		4000: "Subcategory cannot be created inside a Folder, if a Guide is already created",
		4001: "If a user is already a Super Admin, you cannot change the User Role",
		4002: "This action is not allowed on a published guide",
		4003: "Locked guide cannot be published",
		4004: "This action is not allowed on published Folder. Please unpublish it",
		4006: "Application must belong to the given organization",
		4007: "You are not authorised to perform this action",
		4008: "Action is not allowed for this Subcategory",
		4009: "Guide must be published",
		4010: "Guide cannot be created inside a folder with a subcategory",
		4011: "To create step(s), you need to unlock this guide",
		4012: "To edit step(s), you need to unlock this guide",
		4013: "To delete step(s), you need to unlock this guide",
		4014: "To copy and paste step(s), you need to unlock this guide",
		3001: "Guide will be available for export soon. To check the status go to 'Task Status' under account menu",
		3002: "Upload started. Please do not refresh or close the browser until upload is completed. You can check the import status once upload is completed",
		3003: "User already exists",
		3004: "Email ID is already verified",
		3005: "This URL is conflicting with other application configuration, please try to add any other URL",
		3006: "Folder must belong to the same application",
		3007: "Domain already exists",
		3008: "You have reached the maximum limit to create guides",
		3009: "Survey already exists in given guide",
		3010: "The Step must belong to the same guide",
		3011: "This Organization is suspended. Please contact your Administrator",
		3012: "Guide(s) must belong to the same folder",
		3013: "This guide already exists with the given pair of object and field name",
		3014: "User suspended",
		3015: "User already verified",
		3016: "This feature is disabled on HPE",
		3017: "OTP has been sent successfully to your email address",
		3018: "Role already exists",
		3019: "Country already exists",
		3020: "City already exists",
		3021: "This org is not connected to your YouTube channel. Please connect it",
		3022: "YouTube publishing in progress",
		3023: "Your organization is not verified. For help, please contact support @edcast.com",
		3024: "JSON file is not available for this organization",
		3025: "We ran into a problem during authentication. Please try this again. If the problem persists refresh the page and try again",
		3026: "JSON file is not available for this guide",
		3027: "No step available. Create at least one step to publish the guide",
		3028: "Maximum tour publish limit reached"
	}
};

export const LABELS_TAB = {
    knowledgeCloudTab: "LXP",
	allGuidesTab: "All Guides",
	exportTab: "Export",
	importTab: "Import",
	myTeamTab: "",
	currentPageTab: "Current Page",
	myChat: "MyChat"
};